# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: BTL Documentation
email: n@p12a.org.uk
description: > # this means to ignore newlines until "baseurl:"
  Documentation for my toy language.
baseurl: "/btl" # the subpath of your site, e.g. /blog
url: "http://nbaum.github.io" # the base hostname & protocol for your site
twitter_username: parenthephobia
github_username:  nbaum

# Build settings
markdown: kramdown
